[[google-drive-component]]
= Google Drive Component
:docTitle: Google Drive
:artifactId: camel-google-drive
:description: Manage files in Google Drive.
:since: 2.14
:supportLevel: Stable
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:group: Google

*Since Camel {since}*

*{component-header}*

The Google Drive component provides access to the
http://drive.google.com[Google Drive file storage service] via the
https://developers.google.com/drive/v2/reference[Google Drive Web APIs].

Google Drive uses
the https://developers.google.com/accounts/docs/OAuth2[OAuth 2.0
protocol] for authenticating a Google account and authorizing access to
user data. Before you can use this component, you will need to
https://developers.google.com/drive/web/auth/web-server[create an
account and generate OAuth credentials]. Credentials comprise of a
clientId, clientSecret, and a refreshToken. A handy resource for
generating a long-lived refreshToken is the
https://developers.google.com/oauthplayground[OAuth playground].

Maven users will need to add the following dependency to their pom.xml
for this component:

-------------------------------------------------------
    <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-google-drive</artifactId>
            <!-- use the same version as your Camel core version -->
            <version>x.x.x</version>
    </dependency>
        
-------------------------------------------------------

== URI Format

'''''

The GoogleDrive Component uses the following URI format:

---------------------------------------------------------
        google-drive://endpoint-prefix/endpoint?[options]
    
---------------------------------------------------------

Endpoint prefix can be one of:

* drive-about
* drive-apps
* drive-changes
* drive-channels
* drive-children
* drive-comments
* drive-files
* drive-parents
* drive-permissions
* drive-properties
* drive-realtime
* drive-replies
* drive-revisions

== GoogleDriveComponent





// component options: START
The Google Drive component supports 11 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *applicationName* (common) | Google drive application name. Example would be camel-google-drive/1.0 |  | String
| *clientId* (common) | Client ID of the drive application |  | String
| *configuration* (common) | To use the shared configuration |  | GoogleDriveConfiguration
| *scopes* (common) | Specifies the level of permissions you want a drive application to have to a user account. See \https://developers.google.com/drive/web/scopes for more info. |  | List
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *basicPropertyBinding* (advanced) | *Deprecated* Whether the component should use basic property binding (Camel 2.x) or the newer property binding with additional capabilities | false | boolean
| *clientFactory* (advanced) | To use the GoogleCalendarClientFactory as factory for creating the client. Will by default use BatchGoogleDriveClientFactory |  | GoogleDriveClientFactory
| *accessToken* (security) | OAuth 2 access token. This typically expires after an hour so refreshToken is recommended for long term usage. |  | String
| *clientSecret* (security) | Client secret of the drive application |  | String
| *refreshToken* (security) | OAuth 2 refresh token. Using this, the Google Calendar component can obtain a new accessToken whenever the current one expires - a necessity if the application is long-lived. |  | String
|===
// component options: END








// endpoint options: START
The Google Drive endpoint is configured using URI syntax:

----
google-drive:apiName/methodName
----

with the following path and query parameters:

=== Path Parameters (2 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *apiName* | *Required* What kind of operation to perform. There are 13 enums and the value can be one of: drive-about, drive-apps, drive-changes, drive-channels, drive-children, drive-comments, drive-files, drive-parents, drive-permissions, drive-properties, drive-realtime, drive-replies, drive-revisions |  | GoogleDriveApiName
| *methodName* | *Required* What sub operation to use for the selected operation. There are 13 enums and the value can be one of: copy, delete, get, getIdForEmail, insert, list, patch, stop, touch, trash, untrash, update, watch |  | String
|===


=== Query Parameters (30 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *applicationName* (common) | Google drive application name. Example would be camel-google-drive/1.0 |  | String
| *clientFactory* (common) | To use the GoogleCalendarClientFactory as factory for creating the client. Will by default use BatchGoogleDriveClientFactory |  | GoogleDriveClientFactory
| *clientId* (common) | Client ID of the drive application |  | String
| *inBody* (common) | Sets the name of a parameter to be passed in the exchange In Body |  | String
| *scopes* (common) | Specifies the level of permissions you want a drive application to have to a user account. See \https://developers.google.com/drive/web/scopes for more info. |  | List
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *sendEmptyMessageWhenIdle* (consumer) | If the polling consumer did not poll any files, you can enable this option to send an empty message (no body) instead. | false | boolean
| *exceptionHandler* (consumer) | To let the consumer use a custom ExceptionHandler. Notice if the option bridgeErrorHandler is enabled then this option is not in use. By default the consumer will deal with exceptions, that will be logged at WARN or ERROR level and ignored. |  | ExceptionHandler
| *exchangePattern* (consumer) | Sets the exchange pattern when the consumer creates an exchange. There are 3 enums and the value can be one of: in-only, in-out, in-optional-out |  | ExchangePattern
| *pollStrategy* (consumer) | A pluggable org.apache.camel.PollingConsumerPollingStrategy allowing you to provide your custom implementation to control error handling usually occurred during the poll operation before an Exchange have been created and being routed in Camel. |  | PollingConsumerPollStrategy
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *basicPropertyBinding* (advanced) | Whether the endpoint should use basic property binding (Camel 2.x) or the newer property binding with additional capabilities | false | boolean
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used, or Camel is allowed to use asynchronous processing (if supported). | false | boolean
| *backoffErrorThreshold* (scheduler) | The number of subsequent error polls (failed due some error) that should happen before the backoffMultipler should kick-in. |  | int
| *backoffIdleThreshold* (scheduler) | The number of subsequent idle polls that should happen before the backoffMultipler should kick-in. |  | int
| *backoffMultiplier* (scheduler) | To let the scheduled polling consumer backoff if there has been a number of subsequent idles/errors in a row. The multiplier is then the number of polls that will be skipped before the next actual attempt is happening again. When this option is in use then backoffIdleThreshold and/or backoffErrorThreshold must also be configured. |  | int
| *delay* (scheduler) | Milliseconds before the next poll. | 500 | long
| *greedy* (scheduler) | If greedy is enabled, then the ScheduledPollConsumer will run immediately again, if the previous run polled 1 or more messages. | false | boolean
| *initialDelay* (scheduler) | Milliseconds before the first poll starts. | 1000 | long
| *repeatCount* (scheduler) | Specifies a maximum limit of number of fires. So if you set it to 1, the scheduler will only fire once. If you set it to 5, it will only fire five times. A value of zero or negative means fire forever. | 0 | long
| *runLoggingLevel* (scheduler) | The consumer logs a start/complete log line when it polls. This option allows you to configure the logging level for that. There are 6 enums and the value can be one of: trace, debug, info, warn, error, off | trace | LoggingLevel
| *scheduledExecutorService* (scheduler) | Allows for configuring a custom/shared thread pool to use for the consumer. By default each consumer has its own single threaded thread pool. |  | ScheduledExecutorService
| *scheduler* (scheduler) | To use a cron scheduler from either camel-spring or camel-quartz component. Use value spring or quartz for built in scheduler | none | Object
| *schedulerProperties* (scheduler) | To configure additional properties when using a custom scheduler or any of the Quartz, Spring based scheduler. |  | Map
| *startScheduler* (scheduler) | Whether the scheduler should be auto started. | true | boolean
| *timeUnit* (scheduler) | Time unit for initialDelay and delay options. There are 7 enums and the value can be one of: nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days | milliseconds | TimeUnit
| *useFixedDelay* (scheduler) | Controls if fixed delay or fixed rate is used. See ScheduledExecutorService in JDK for details. | true | boolean
| *accessToken* (security) | OAuth 2 access token. This typically expires after an hour so refreshToken is recommended for long term usage. |  | String
| *clientSecret* (security) | Client secret of the drive application |  | String
| *refreshToken* (security) | OAuth 2 refresh token. Using this, the Google Calendar component can obtain a new accessToken whenever the current one expires - a necessity if the application is long-lived. |  | String
|===




=== Query API Parameters (12 APIs):

The Google Drive endpoint is an API based component and has additional parameters based on which API name and method in use.
The API name and method is located in the endpoint URI as the apiName/methodName path parameters:

----
google-drive:apiName/methodName
----

The following lists each API name and method and its additional parameters.


==== drive-channels


The drive-channels has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Channels$Stop stop(com.google.api.services.drive.model.Channel content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| stop | *contentChannel* | The com.google.api.services.drive.model.Channel | Channel
|===




==== drive-revisions


The drive-revisions has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Revisions$Delete delete(String fileId, String revisionId)
com.google.api.services.drive.Drive$Revisions$Get get(String fileId, String revisionId)
com.google.api.services.drive.Drive$Revisions$List list(String fileId)
com.google.api.services.drive.Drive$Revisions$Patch patch(String fileId, String revisionId, com.google.api.services.drive.model.Revision content)
com.google.api.services.drive.Drive$Revisions$Update update(String fileId, String revisionId, com.google.api.services.drive.model.Revision content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *fileId* | The ID of the file | String
| delete | *revisionId* | The ID of the revision | String
| get | *fileId* | The ID of the file | String
| get | *revisionId* | The ID of the revision | String
| list | *fileId* | The ID of the file | String
| patch | *content* | The com.google.api.services.drive.model.Revision | Revision
| patch | *fileId* | The ID for the file | String
| patch | *revisionId* | The ID for the revision | String
| update | *content* | The com.google.api.services.drive.model.Revision | Revision
| update | *fileId* | The ID for the file | String
| update | *revisionId* | The ID for the revision | String
|===




==== drive-replies


The drive-replies has 6 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Replies$Delete delete(String fileId, String commentId, String replyId)
com.google.api.services.drive.Drive$Replies$Get get(String fileId, String commentId, String replyId)
com.google.api.services.drive.Drive$Replies$Insert insert(String fileId, String commentId, com.google.api.services.drive.model.CommentReply content)
com.google.api.services.drive.Drive$Replies$List list(String fileId, String commentId)
com.google.api.services.drive.Drive$Replies$Patch patch(String fileId, String commentId, String replyId, com.google.api.services.drive.model.CommentReply content)
com.google.api.services.drive.Drive$Replies$Update update(String fileId, String commentId, String replyId, com.google.api.services.drive.model.CommentReply content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *commentId* | The ID of the comment | String
| delete | *fileId* | The ID of the file | String
| delete | *replyId* | The ID of the reply | String
| get | *commentId* | The ID of the comment | String
| get | *fileId* | The ID of the file | String
| get | *replyId* | The ID of the reply | String
| insert | *commentId* | The ID of the comment | String
| insert | *content* | The com.google.api.services.drive.model.CommentReply | CommentReply
| insert | *fileId* | The ID of the file | String
| list | *commentId* | The ID of the comment | String
| list | *fileId* | The ID of the file | String
| patch | *commentId* | The ID of the comment | String
| patch | *content* | The com.google.api.services.drive.model.CommentReply | CommentReply
| patch | *fileId* | The ID of the file | String
| patch | *replyId* | The ID of the reply | String
| update | *commentId* | The ID of the comment | String
| update | *content* | The com.google.api.services.drive.model.CommentReply | CommentReply
| update | *fileId* | The ID of the file | String
| update | *replyId* | The ID of the reply | String
|===




==== drive-permissions


The drive-permissions has 7 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Permissions$Delete delete(String fileId, String permissionId)
com.google.api.services.drive.Drive$Permissions$Get get(String fileId, String permissionId)
com.google.api.services.drive.Drive$Permissions$GetIdForEmail getIdForEmail(String email)
com.google.api.services.drive.Drive$Permissions$Insert insert(String fileId, com.google.api.services.drive.model.Permission content)
com.google.api.services.drive.Drive$Permissions$List list(String fileId)
com.google.api.services.drive.Drive$Permissions$Patch patch(String fileId, String permissionId, com.google.api.services.drive.model.Permission content)
com.google.api.services.drive.Drive$Permissions$Update update(String fileId, String permissionId, com.google.api.services.drive.model.Permission content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *fileId* | The ID for the file or Team Drive | String
| delete | *permissionId* | The ID for the permission | String
| get | *fileId* | The ID for the file or Team Drive | String
| get | *permissionId* | The ID for the permission | String
| getIdForEmail | *email* | The email address for which to return a permission ID | String
| insert | *content* | The com.google.api.services.drive.model.Permission | Permission
| insert | *fileId* | The ID for the file or Team Drive | String
| list | *fileId* | The ID for the file or Team Drive | String
| patch | *content* | The com.google.api.services.drive.model.Permission | Permission
| patch | *fileId* | The ID for the file or Team Drive | String
| patch | *permissionId* | The ID for the permission | String
| update | *content* | The com.google.api.services.drive.model.Permission | Permission
| update | *fileId* | The ID for the file or Team Drive | String
| update | *permissionId* | The ID for the permission | String
|===




==== drive-parents


The drive-parents has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Parents$Delete delete(String fileId, String parentId)
com.google.api.services.drive.Drive$Parents$Get get(String fileId, String parentId)
com.google.api.services.drive.Drive$Parents$Insert insert(String fileId, com.google.api.services.drive.model.ParentReference content)
com.google.api.services.drive.Drive$Parents$List list(String fileId)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *fileId* | The ID of the file | String
| delete | *parentId* | The ID of the parent | String
| get | *fileId* | The ID of the file | String
| get | *parentId* | The ID of the parent | String
| insert | *content* | The com.google.api.services.drive.model.ParentReference | ParentReference
| insert | *fileId* | The ID of the file | String
| list | *fileId* | The ID of the file | String
|===




==== drive-apps


The drive-apps has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Apps$Get get(String appId)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| get | *appId* | The ID of the app | String
|===




==== drive-changes


The drive-changes has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Changes$Get get(String changeId)
com.google.api.services.drive.Drive$Changes$Watch watch(com.google.api.services.drive.model.Channel content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| get | *changeId* | The ID of the change | String
| watch | *contentChannel* | The com.google.api.services.drive.model.Channel | Channel
|===




==== drive-comments


The drive-comments has 6 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Comments$Delete delete(String fileId, String commentId)
com.google.api.services.drive.Drive$Comments$Get get(String fileId, String commentId)
com.google.api.services.drive.Drive$Comments$Insert insert(String fileId, com.google.api.services.drive.model.Comment content)
com.google.api.services.drive.Drive$Comments$List list(String fileId)
com.google.api.services.drive.Drive$Comments$Patch patch(String fileId, String commentId, com.google.api.services.drive.model.Comment content)
com.google.api.services.drive.Drive$Comments$Update update(String fileId, String commentId, com.google.api.services.drive.model.Comment content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *commentId* | The ID of the comment | String
| delete | *fileId* | The ID of the file | String
| get | *commentId* | The ID of the comment | String
| get | *fileId* | The ID of the file | String
| insert | *content* | The com.google.api.services.drive.model.Comment | Comment
| insert | *fileId* | The ID of the file | String
| list | *fileId* | The ID of the file | String
| patch | *commentId* | The ID of the comment | String
| patch | *content* | The com.google.api.services.drive.model.Comment | Comment
| patch | *fileId* | The ID of the file | String
| update | *commentId* | The ID of the comment | String
| update | *content* | The com.google.api.services.drive.model.Comment | Comment
| update | *fileId* | The ID of the file | String
|===




==== drive-properties


The drive-properties has 6 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Properties$Delete delete(String fileId, String propertyKey)
com.google.api.services.drive.Drive$Properties$Get get(String fileId, String propertyKey)
com.google.api.services.drive.Drive$Properties$Insert insert(String fileId, com.google.api.services.drive.model.Property content)
com.google.api.services.drive.Drive$Properties$List list(String fileId)
com.google.api.services.drive.Drive$Properties$Patch patch(String fileId, String propertyKey, com.google.api.services.drive.model.Property content)
com.google.api.services.drive.Drive$Properties$Update update(String fileId, String propertyKey, com.google.api.services.drive.model.Property content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *fileId* | The ID of the file | String
| delete | *propertyKey* | The key of the property | String
| get | *fileId* | The ID of the file | String
| get | *propertyKey* | The key of the property | String
| insert | *content* | The com.google.api.services.drive.model.Property | Property
| insert | *fileId* | The ID of the file | String
| list | *fileId* | The ID of the file | String
| patch | *content* | The com.google.api.services.drive.model.Property | Property
| patch | *fileId* | The ID of the file | String
| patch | *propertyKey* | The key of the property | String
| update | *content* | The com.google.api.services.drive.model.Property | Property
| update | *fileId* | The ID of the file | String
| update | *propertyKey* | The key of the property | String
|===




==== drive-realtime


The drive-realtime has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Realtime$Get get(String fileId)
com.google.api.services.drive.Drive$Realtime$Update update(String fileId)
com.google.api.services.drive.Drive$Realtime$Update update(String fileId, com.google.api.client.http.AbstractInputStreamContent mediaContent)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| get | *fileId* | The ID of the file that the Realtime API data model is associated with | String
| update | *fileId* | The ID of the file that the Realtime API data model is associated with | String
| update | *mediaContent* | The media HTTP content or null if none | AbstractInputStreamContent
|===




==== drive-children


The drive-children has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Children$Delete delete(String folderId, String childId)
com.google.api.services.drive.Drive$Children$Get get(String folderId, String childId)
com.google.api.services.drive.Drive$Children$Insert insert(String folderId, com.google.api.services.drive.model.ChildReference content)
com.google.api.services.drive.Drive$Children$List list(String folderId)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| delete | *childId* | The ID of the child | String
| delete | *folderId* | The ID of the folder | String
| get | *childId* | The ID of the child | String
| get | *folderId* | The ID of the folder | String
| insert | *content* | The com.google.api.services.drive.model.ChildReference | ChildReference
| insert | *folderId* | The ID of the folder | String
| list | *folderId* | The ID of the folder | String
|===




==== drive-files


The drive-files has 11 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.google.api.services.drive.Drive$Files$Copy copy(String fileId, com.google.api.services.drive.model.File content)
com.google.api.services.drive.Drive$Files$Delete delete(String fileId)
com.google.api.services.drive.Drive$Files$Export export(String fileId, String mimeType)
com.google.api.services.drive.Drive$Files$Get get(String fileId)
com.google.api.services.drive.Drive$Files$Insert insert(com.google.api.services.drive.model.File content)
com.google.api.services.drive.Drive$Files$Insert insert(com.google.api.services.drive.model.File content, com.google.api.client.http.AbstractInputStreamContent mediaContent)
com.google.api.services.drive.Drive$Files$Patch patch(String fileId, com.google.api.services.drive.model.File content)
com.google.api.services.drive.Drive$Files$Touch touch(String fileId)
com.google.api.services.drive.Drive$Files$Trash trash(String fileId)
com.google.api.services.drive.Drive$Files$Untrash untrash(String fileId)
com.google.api.services.drive.Drive$Files$Update update(String fileId, com.google.api.services.drive.model.File content)
com.google.api.services.drive.Drive$Files$Update update(String fileId, com.google.api.services.drive.model.File content, com.google.api.client.http.AbstractInputStreamContent mediaContent)
com.google.api.services.drive.Drive$Files$Watch watch(String fileId, com.google.api.services.drive.model.Channel content)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| copy | *content* | The com.google.api.services.drive.model.File | File
| copy | *fileId* | The ID of the file to copy | String
| delete | *fileId* | The ID of the file to delete | String
| export | *fileId* | The ID of the file | String
| export | *mimeType* | The MIME type of the format requested for this export | String
| get | *fileId* | The ID for the file in question | String
| insert | *content* | The com.google.api.services.drive.model.File media metadata or null if none | File
| insert | *mediaContent* | The media HTTP content or null if none | AbstractInputStreamContent
| patch | *content* | The com.google.api.services.drive.model.File | File
| patch | *fileId* | The ID of the file to update | String
| touch | *fileId* | The ID of the file to update | String
| trash | *fileId* | The ID of the file to trash | String
| untrash | *fileId* | The ID of the file to untrash | String
| update | *content* | The com.google.api.services.drive.model.File media metadata or null if none | File
| update | *fileId* | The ID of the file to update | String
| update | *mediaContent* | The media HTTP content or null if none | AbstractInputStreamContent
| watch | *contentChannel* | The com.google.api.services.drive.model.Channel | Channel
| watch | *fileId* | The ID for the file in question | String
|===
// endpoint options: END




== Producer Endpoints

Producer endpoints can use endpoint prefixes followed by endpoint names
and associated options described next. A shorthand alias can be used for
some endpoints. The endpoint URI MUST contain a prefix.

Endpoint options that are not mandatory are denoted by []. When there
are no mandatory options for an endpoint, one of the set of [] options
MUST be provided. Producer endpoints can also use a special option
*`inBody`* that in turn should contain the name of the endpoint option
whose value will be contained in the Camel Exchange In message.

Any of the endpoint options can be provided in either the endpoint URI,
or dynamically in a message header. The message header name must be of
the format `CamelGoogleDrive.<option>`. Note that the `inBody` option
overrides message header, i.e. the endpoint option `inBody=option` would
override a `CamelGoogleDrive.option` header.

For more information on the endpoints and options see API documentation
at: https://developers.google.com/drive/v2/reference/[https://developers.google.com/drive/v2/reference/]

== Consumer Endpoints

Any of the producer endpoints can be used as a consumer endpoint.
Consumer endpoints can use
http://camel.apache.org/polling-consumer.html#PollingConsumer-ScheduledPollConsumerOptions[Scheduled
Poll Consumer Options] to schedule endpoint invocation.
Consumer endpoints that return an array or collection will
generate one exchange per element, and their routes will be executed
once for each exchange.

== Message Headers

Any URI option can be provided in a message header for producer
endpoints with a `CamelGoogleDrive.` prefix.

== Message Body

All result message bodies utilize objects provided by the underlying
APIs used by the GoogleDriveComponent. Producer endpoints can specify
the option name for incoming message body in the `inBody` endpoint URI
parameter. For endpoints that return an array or collection, a consumer
endpoint will map every element to distinct messages.     

include::camel-spring-boot::page$google-drive-starter.adoc[]
