[[twilio-component]]
= Twilio Component
:docTitle: Twilio
:artifactId: camel-twilio
:description: Interact with Twilio REST APIs using Twilio Java SDK.
:since: 2.20
:supportLevel: Stable
:component-header: Both producer and consumer are supported

*Since Camel {since}*

*{component-header}*

The Twilio component provides access to Version 2010-04-01 of Twilio REST APIs accessible
using https://github.com/twilio/twilio-java[Twilio Java SDK].

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-twilio</artifactId>
    <version>${camel-version}</version>
</dependency>
----


== Twilio Options

// component options: START
The Twilio component supports 8 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *basicPropertyBinding* (advanced) | *Deprecated* Whether the component should use basic property binding (Camel 2.x) or the newer property binding with additional capabilities | false | boolean
| *configuration* (advanced) | To use the shared configuration |  | TwilioConfiguration
| *restClient* (advanced) | To use the shared REST client |  | TwilioRestClient
| *accountSid* (security) | The account SID to use. |  | String
| *password* (security) | Auth token for the account. |  | String
| *username* (security) | The account to use. |  | String
|===
// component options: END

// endpoint options: START
The Twilio endpoint is configured using URI syntax:

----
twilio:apiName/methodName
----

with the following path and query parameters:

=== Path Parameters (2 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *apiName* | *Required* What kind of operation to perform. There are 56 enums and the value can be one of: account, address, application, available-phone-number-country, call, conference, connect-app, incoming-phone-number, key, message, new-key, new-signing-key, notification, outgoing-caller-id, queue, recording, short-code, signing-key, token, transcription, validation-request, address-dependent-phone-number, available-phone-number-country-local, available-phone-number-country-mobile, available-phone-number-country-toll-free, call-feedback, call-feedback-summary, call-notification, call-recording, conference-participant, incoming-phone-number-local, incoming-phone-number-mobile, incoming-phone-number-toll-free, message-feedback, message-media, queue-member, recording-add-on-result, recording-transcription, recording-add-on-result-payload, sip-credential-list, sip-domain, sip-ip-access-control-list, sip-credential-list-credential, sip-domain-credential-list-mapping, sip-domain-ip-access-control-list-mapping, sip-ip-access-control-list-ip-address, usage-record, usage-trigger, usage-record-all-time, usage-record-daily, usage-record-last-month, usage-record-monthly, usage-record-this-month, usage-record-today, usage-record-yearly, usage-record-yesterday |  | TwilioApiName
| *methodName* | *Required* What sub operation to use for the selected operation. There are 5 enums and the value can be one of: create, delete, fetch, read, update |  | String
|===


=== Query Parameters (23 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *inBody* (common) | Sets the name of a parameter to be passed in the exchange In Body |  | String
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *sendEmptyMessageWhenIdle* (consumer) | If the polling consumer did not poll any files, you can enable this option to send an empty message (no body) instead. | false | boolean
| *exceptionHandler* (consumer) | To let the consumer use a custom ExceptionHandler. Notice if the option bridgeErrorHandler is enabled then this option is not in use. By default the consumer will deal with exceptions, that will be logged at WARN or ERROR level and ignored. |  | ExceptionHandler
| *exchangePattern* (consumer) | Sets the exchange pattern when the consumer creates an exchange. There are 3 enums and the value can be one of: in-only, in-out, in-optional-out |  | ExchangePattern
| *pollStrategy* (consumer) | A pluggable org.apache.camel.PollingConsumerPollingStrategy allowing you to provide your custom implementation to control error handling usually occurred during the poll operation before an Exchange have been created and being routed in Camel. |  | PollingConsumerPollStrategy
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *basicPropertyBinding* (advanced) | Whether the endpoint should use basic property binding (Camel 2.x) or the newer property binding with additional capabilities | false | boolean
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used, or Camel is allowed to use asynchronous processing (if supported). | false | boolean
| *backoffErrorThreshold* (scheduler) | The number of subsequent error polls (failed due some error) that should happen before the backoffMultipler should kick-in. |  | int
| *backoffIdleThreshold* (scheduler) | The number of subsequent idle polls that should happen before the backoffMultipler should kick-in. |  | int
| *backoffMultiplier* (scheduler) | To let the scheduled polling consumer backoff if there has been a number of subsequent idles/errors in a row. The multiplier is then the number of polls that will be skipped before the next actual attempt is happening again. When this option is in use then backoffIdleThreshold and/or backoffErrorThreshold must also be configured. |  | int
| *delay* (scheduler) | Milliseconds before the next poll. | 500 | long
| *greedy* (scheduler) | If greedy is enabled, then the ScheduledPollConsumer will run immediately again, if the previous run polled 1 or more messages. | false | boolean
| *initialDelay* (scheduler) | Milliseconds before the first poll starts. | 1000 | long
| *repeatCount* (scheduler) | Specifies a maximum limit of number of fires. So if you set it to 1, the scheduler will only fire once. If you set it to 5, it will only fire five times. A value of zero or negative means fire forever. | 0 | long
| *runLoggingLevel* (scheduler) | The consumer logs a start/complete log line when it polls. This option allows you to configure the logging level for that. There are 6 enums and the value can be one of: trace, debug, info, warn, error, off | trace | LoggingLevel
| *scheduledExecutorService* (scheduler) | Allows for configuring a custom/shared thread pool to use for the consumer. By default each consumer has its own single threaded thread pool. |  | ScheduledExecutorService
| *scheduler* (scheduler) | To use a cron scheduler from either camel-spring or camel-quartz component. Use value spring or quartz for built in scheduler | none | Object
| *schedulerProperties* (scheduler) | To configure additional properties when using a custom scheduler or any of the Quartz, Spring based scheduler. |  | Map
| *startScheduler* (scheduler) | Whether the scheduler should be auto started. | true | boolean
| *timeUnit* (scheduler) | Time unit for initialDelay and delay options. There are 7 enums and the value can be one of: nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days | milliseconds | TimeUnit
| *useFixedDelay* (scheduler) | Controls if fixed delay or fixed rate is used. See ScheduledExecutorService in JDK for details. | true | boolean
|===




=== Query API Parameters (56 APIs):

The Twilio endpoint is an API based component and has additional parameters based on which API name and method in use.
The API name and method is located in the endpoint URI as the apiName/methodName path parameters:

----
twilio:apiName/methodName
----

The following lists each API name and method and its additional parameters.


==== recording-add-on-result-payload


The recording-add-on-result-payload has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.recording.addonresult.PayloadDeleter deleter(String pathAccountSid, String pathReferenceSid, String pathAddOnResultSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.addonresult.PayloadDeleter deleter(String pathReferenceSid, String pathAddOnResultSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.addonresult.PayloadFetcher fetcher(String pathAccountSid, String pathReferenceSid, String pathAddOnResultSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.addonresult.PayloadFetcher fetcher(String pathReferenceSid, String pathAddOnResultSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.addonresult.PayloadReader reader(String pathAccountSid, String pathReferenceSid, String pathAddOnResultSid)
com.twilio.rest.api.v2010.account.recording.addonresult.PayloadReader reader(String pathReferenceSid, String pathAddOnResultSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathAddOnResultSid* | The SID of the AddOnResult to which the payloads to delete belongs | String
| deleter | *pathReferenceSid* | The SID of the recording to which the AddOnResult resource that contains the payloads to delete belongs | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathAddOnResultSid* | The SID of the AddOnResult to which the payloads to delete belongs | String
| fetcher | *pathReferenceSid* | The SID of the recording to which the AddOnResult resource that contains the payloads to delete belongs | String
| fetcher | *pathSid* | The unique string that identifies the resource to fetch | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathAddOnResultSid* | The SID of the AddOnResult to which the payloads to delete belongs | String
| reader | *pathReferenceSid* | The SID of the recording to which the AddOnResult resource that contains the payloads to delete belongs | String
|===




==== usage-record-today


The usage-record-today has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.TodayReader reader()
com.twilio.rest.api.v2010.account.usage.record.TodayReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== available-phone-number-country-local


The available-phone-number-country-local has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.availablephonenumbercountry.LocalReader reader(String pathAccountSid, String pathCountryCode)
com.twilio.rest.api.v2010.account.availablephonenumbercountry.LocalReader reader(String pathCountryCode)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account requesting the AvailablePhoneNumber resources | String
| reader | *pathCountryCode* | The ISO Country code of the country from which to read phone numbers | String
|===




==== call-recording


The call-recording has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.call.RecordingCreator creator(String pathAccountSid, String pathCallSid)
com.twilio.rest.api.v2010.account.call.RecordingCreator creator(String pathCallSid)
com.twilio.rest.api.v2010.account.call.RecordingDeleter deleter(String pathAccountSid, String pathCallSid, String pathSid)
com.twilio.rest.api.v2010.account.call.RecordingDeleter deleter(String pathCallSid, String pathSid)
com.twilio.rest.api.v2010.account.call.RecordingFetcher fetcher(String pathAccountSid, String pathCallSid, String pathSid)
com.twilio.rest.api.v2010.account.call.RecordingFetcher fetcher(String pathCallSid, String pathSid)
com.twilio.rest.api.v2010.account.call.RecordingReader reader(String pathAccountSid, String pathCallSid)
com.twilio.rest.api.v2010.account.call.RecordingReader reader(String pathCallSid)
com.twilio.rest.api.v2010.account.call.RecordingUpdater updater(String pathAccountSid, String pathCallSid, String pathSid, com.twilio.rest.api.v2010.account.call.Recording$Status status)
com.twilio.rest.api.v2010.account.call.RecordingUpdater updater(String pathCallSid, String pathSid, com.twilio.rest.api.v2010.account.call.Recording$Status status)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *pathCallSid* | The SID of the Call to associate the resource with | String
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathCallSid* | The SID of the Call to associate the resource with | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathCallSid* | The SID of the Call to associate the resource with | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathCallSid* | The SID of the Call to associate the resource with | String
| updater | *pathAccountSid* | The SID of the Account that created the resource to update | String
| updater | *pathCallSid* | The SID of the Call to associate the resource with | String
| updater | *pathSid* | The unique string that identifies the resource | String
| updater | *status* | The new status of the recording | Status
|===




==== queue-member


The queue-member has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.queue.MemberFetcher fetcher(String pathAccountSid, String pathQueueSid, String pathCallSid)
com.twilio.rest.api.v2010.account.queue.MemberFetcher fetcher(String pathQueueSid, String pathCallSid)
com.twilio.rest.api.v2010.account.queue.MemberReader reader(String pathAccountSid, String pathQueueSid)
com.twilio.rest.api.v2010.account.queue.MemberReader reader(String pathQueueSid)
com.twilio.rest.api.v2010.account.queue.MemberUpdater updater(String pathAccountSid, String pathQueueSid, String pathCallSid, java.net.URI url)
com.twilio.rest.api.v2010.account.queue.MemberUpdater updater(String pathQueueSid, String pathCallSid, java.net.URI url)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| fetcher | *pathCallSid* | The Call SID of the resource(s) to fetch | String
| fetcher | *pathQueueSid* | The SID of the Queue in which to find the members | String
| reader | *pathAccountSid* | The SID of the Account that created the resource(s) to read | String
| reader | *pathQueueSid* | The SID of the Queue in which to find the members | String
| updater | *pathAccountSid* | The SID of the Account that created the resource(s) to update | String
| updater | *pathCallSid* | The Call SID of the resource(s) to update | String
| updater | *pathQueueSid* | The SID of the Queue in which to find the members | String
| updater | *url* | The absolute URL of the Queue resource | URI
|===




==== usage-trigger


The usage-trigger has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.TriggerCreator creator(String pathAccountSid, java.net.URI callbackUrl, String triggerValue, com.twilio.rest.api.v2010.account.usage.Trigger$UsageCategory usageCategory)
com.twilio.rest.api.v2010.account.usage.TriggerCreator creator(java.net.URI callbackUrl, String triggerValue, com.twilio.rest.api.v2010.account.usage.Trigger$UsageCategory usageCategory)
com.twilio.rest.api.v2010.account.usage.TriggerDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.usage.TriggerDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.usage.TriggerFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.usage.TriggerFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.usage.TriggerReader reader()
com.twilio.rest.api.v2010.account.usage.TriggerReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.usage.TriggerUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.usage.TriggerUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *callbackUrl* | The URL we call when the trigger fires | URI
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *triggerValue* | The usage value at which the trigger should fire | String
| creator | *usageCategory* | The usage category the trigger watches | UsageCategory
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resources to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== usage-record-last-month


The usage-record-last-month has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.LastMonthReader reader()
com.twilio.rest.api.v2010.account.usage.record.LastMonthReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== usage-record-all-time


The usage-record-all-time has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.AllTimeReader reader()
com.twilio.rest.api.v2010.account.usage.record.AllTimeReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== recording-transcription


The recording-transcription has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.recording.TranscriptionDeleter deleter(String pathAccountSid, String pathRecordingSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.TranscriptionDeleter deleter(String pathRecordingSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.TranscriptionFetcher fetcher(String pathAccountSid, String pathRecordingSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.TranscriptionFetcher fetcher(String pathRecordingSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.TranscriptionReader reader(String pathAccountSid, String pathRecordingSid)
com.twilio.rest.api.v2010.account.recording.TranscriptionReader reader(String pathRecordingSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathRecordingSid* | The SID of the recording that created the transcription to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathRecordingSid* | The SID of the recording that created the transcription to delete | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathRecordingSid* | The SID of the recording that created the transcription to delete | String
|===




==== message


The message has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.MessageCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber to, String messagingServiceSid, String body)
com.twilio.rest.api.v2010.account.MessageCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber to, String messagingServiceSid, java.util.List<java.net.URI> mediaUrl)
com.twilio.rest.api.v2010.account.MessageCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber to, com.twilio.type.PhoneNumber from, String body)
com.twilio.rest.api.v2010.account.MessageCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber to, com.twilio.type.PhoneNumber from, java.util.List<java.net.URI> mediaUrl)
com.twilio.rest.api.v2010.account.MessageCreator creator(com.twilio.type.PhoneNumber to, String messagingServiceSid, String body)
com.twilio.rest.api.v2010.account.MessageCreator creator(com.twilio.type.PhoneNumber to, String messagingServiceSid, java.util.List<java.net.URI> mediaUrl)
com.twilio.rest.api.v2010.account.MessageCreator creator(com.twilio.type.PhoneNumber to, com.twilio.type.PhoneNumber from, String body)
com.twilio.rest.api.v2010.account.MessageCreator creator(com.twilio.type.PhoneNumber to, com.twilio.type.PhoneNumber from, java.util.List<java.net.URI> mediaUrl)
com.twilio.rest.api.v2010.account.MessageDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.MessageDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.MessageFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.MessageFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.MessageReader reader()
com.twilio.rest.api.v2010.account.MessageReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.MessageUpdater updater(String pathAccountSid, String pathSid, String body)
com.twilio.rest.api.v2010.account.MessageUpdater updater(String pathSid, String body)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *body* | The text of the message you want to send. Can be up to 1,600 characters in length. | String
| creator | *from* | The phone number that initiated the message | PhoneNumber
| creator | *mediaUrl* | The URL of the media to send with the message | List
| creator | *messagingServiceSid* | The SID of the Messaging Service you want to associate with the message | String
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *to* | The destination phone number | PhoneNumber
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *body* | The text of the message you want to send | String
| updater | *pathAccountSid* | The SID of the Account that created the resources to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== call-feedback-summary


The call-feedback-summary has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.call.FeedbackSummaryCreator creator(String pathAccountSid, org.joda.time.LocalDate startDate, org.joda.time.LocalDate endDate)
com.twilio.rest.api.v2010.account.call.FeedbackSummaryCreator creator(org.joda.time.LocalDate startDate, org.joda.time.LocalDate endDate)
com.twilio.rest.api.v2010.account.call.FeedbackSummaryDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.call.FeedbackSummaryDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.call.FeedbackSummaryFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.call.FeedbackSummaryFetcher fetcher(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *endDate* | Only include feedback given on or before this date | LocalDate
| creator | *pathAccountSid* | The unique sid that identifies this account | String
| creator | *startDate* | Only include feedback given on or after this date | LocalDate
| deleter | *pathAccountSid* | The unique sid that identifies this account | String
| deleter | *pathSid* | A string that uniquely identifies this feedback summary resource | String
| fetcher | *pathAccountSid* | The unique sid that identifies this account | String
| fetcher | *pathSid* | A string that uniquely identifies this feedback summary resource | String
|===




==== sip-credential-list-credential


The sip-credential-list-credential has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialCreator creator(String pathAccountSid, String pathCredentialListSid, String username, String password)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialCreator creator(String pathCredentialListSid, String username, String password)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialDeleter deleter(String pathAccountSid, String pathCredentialListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialDeleter deleter(String pathCredentialListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialFetcher fetcher(String pathAccountSid, String pathCredentialListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialFetcher fetcher(String pathCredentialListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialReader reader(String pathAccountSid, String pathCredentialListSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialReader reader(String pathCredentialListSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialUpdater updater(String pathAccountSid, String pathCredentialListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.credentiallist.CredentialUpdater updater(String pathCredentialListSid, String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *password* | The password will not be returned in the response | String
| creator | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| creator | *pathCredentialListSid* | The unique id that identifies the credential list to include the created credential | String
| creator | *username* | The username for this credential | String
| deleter | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| deleter | *pathCredentialListSid* | The unique id that identifies the credential list to include the created credential | String
| deleter | *pathSid* | The unique id that identifies the resource to delete | String
| fetcher | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| fetcher | *pathCredentialListSid* | The unique id that identifies the credential list to include the created credential | String
| fetcher | *pathSid* | The unique id that identifies the resource to fetch | String
| reader | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| reader | *pathCredentialListSid* | The unique id that identifies the credential list to include the created credential | String
| updater | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| updater | *pathCredentialListSid* | The unique id that identifies the credential list to include the created credential | String
| updater | *pathSid* | The unique id that identifies the resource to update | String
|===




==== new-key


The new-key has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.NewKeyCreator creator()
com.twilio.rest.api.v2010.account.NewKeyCreator creator(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will be responsible for the new Key resource | String
|===




==== incoming-phone-number


The incoming-phone-number has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.IncomingPhoneNumberCreator creator(String areaCode)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberCreator creator(String pathAccountSid, String areaCode)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberCreator creator(com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberReader reader()
com.twilio.rest.api.v2010.account.IncomingPhoneNumberReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.IncomingPhoneNumberUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *areaCode* | The desired area code for the new phone number | String
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *phoneNumber* | The phone number to purchase in E.164 format | PhoneNumber
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resource to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== call-notification


The call-notification has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.call.NotificationFetcher fetcher(String pathAccountSid, String pathCallSid, String pathSid)
com.twilio.rest.api.v2010.account.call.NotificationFetcher fetcher(String pathCallSid, String pathSid)
com.twilio.rest.api.v2010.account.call.NotificationReader reader(String pathAccountSid, String pathCallSid)
com.twilio.rest.api.v2010.account.call.NotificationReader reader(String pathCallSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathCallSid* | The Call SID of the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathCallSid* | The Call SID of the resource to fetch | String
|===




==== validation-request


The validation-request has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.ValidationRequestCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.ValidationRequestCreator creator(com.twilio.type.PhoneNumber phoneNumber)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account responsible for the new Caller ID | String
| creator | *phoneNumber* | The phone number to verify in E.164 format | PhoneNumber
|===




==== usage-record-yesterday


The usage-record-yesterday has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.YesterdayReader reader()
com.twilio.rest.api.v2010.account.usage.record.YesterdayReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== usage-record-this-month


The usage-record-this-month has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.ThisMonthReader reader()
com.twilio.rest.api.v2010.account.usage.record.ThisMonthReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== new-signing-key


The new-signing-key has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.NewSigningKeyCreator creator()
com.twilio.rest.api.v2010.account.NewSigningKeyCreator creator(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will be responsible for the new Key resource | String
|===




==== conference


The conference has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.ConferenceFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ConferenceFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.ConferenceReader reader()
com.twilio.rest.api.v2010.account.ConferenceReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.ConferenceUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ConferenceUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| fetcher | *pathSid* | The unique string that identifies this resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resource(s) to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resource(s) to update | String
| updater | *pathSid* | The unique string that identifies this resource | String
|===




==== usage-record-daily


The usage-record-daily has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.DailyReader reader()
com.twilio.rest.api.v2010.account.usage.record.DailyReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== application


The application has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.ApplicationCreator creator()
com.twilio.rest.api.v2010.account.ApplicationCreator creator(String pathAccountSid)
com.twilio.rest.api.v2010.account.ApplicationDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ApplicationDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.ApplicationFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ApplicationFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.ApplicationReader reader()
com.twilio.rest.api.v2010.account.ApplicationReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.ApplicationUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ApplicationUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that will create the resource | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== usage-record


The usage-record has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.RecordReader reader()
com.twilio.rest.api.v2010.account.usage.RecordReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== available-phone-number-country-mobile


The available-phone-number-country-mobile has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.availablephonenumbercountry.MobileReader reader(String pathAccountSid, String pathCountryCode)
com.twilio.rest.api.v2010.account.availablephonenumbercountry.MobileReader reader(String pathCountryCode)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account requesting the AvailablePhoneNumber resources | String
| reader | *pathCountryCode* | The ISO Country code of the country from which to read phone numbers | String
|===




==== conference-participant


The conference-participant has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.conference.ParticipantCreator creator(String pathAccountSid, String pathConferenceSid, com.twilio.type.PhoneNumber from, com.twilio.type.PhoneNumber to)
com.twilio.rest.api.v2010.account.conference.ParticipantCreator creator(String pathConferenceSid, com.twilio.type.PhoneNumber from, com.twilio.type.PhoneNumber to)
com.twilio.rest.api.v2010.account.conference.ParticipantDeleter deleter(String pathAccountSid, String pathConferenceSid, String pathCallSid)
com.twilio.rest.api.v2010.account.conference.ParticipantDeleter deleter(String pathConferenceSid, String pathCallSid)
com.twilio.rest.api.v2010.account.conference.ParticipantFetcher fetcher(String pathAccountSid, String pathConferenceSid, String pathCallSid)
com.twilio.rest.api.v2010.account.conference.ParticipantFetcher fetcher(String pathConferenceSid, String pathCallSid)
com.twilio.rest.api.v2010.account.conference.ParticipantReader reader(String pathAccountSid, String pathConferenceSid)
com.twilio.rest.api.v2010.account.conference.ParticipantReader reader(String pathConferenceSid)
com.twilio.rest.api.v2010.account.conference.ParticipantUpdater updater(String pathAccountSid, String pathConferenceSid, String pathCallSid)
com.twilio.rest.api.v2010.account.conference.ParticipantUpdater updater(String pathConferenceSid, String pathCallSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *from* | The phone number, Client identifier, or username portion of SIP address that made this call. | PhoneNumber
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *pathConferenceSid* | The SID of the participant's conference | String
| creator | *to* | The phone number, SIP address or Client identifier that received this call. | PhoneNumber
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathCallSid* | The Call SID or URL encoded label of the participant to delete | String
| deleter | *pathConferenceSid* | The SID of the participant's conference | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathCallSid* | The Call SID or URL encoded label of the participant to fetch | String
| fetcher | *pathConferenceSid* | The SID of the participant's conference | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathConferenceSid* | The SID of the participant's conference | String
| updater | *pathAccountSid* | The SID of the Account that created the resources to update | String
| updater | *pathCallSid* | The Call SID or URL encoded label of the participant to update | String
| updater | *pathConferenceSid* | The SID of the participant's conference | String
|===




==== recording-add-on-result


The recording-add-on-result has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.recording.AddOnResultDeleter deleter(String pathAccountSid, String pathReferenceSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.AddOnResultDeleter deleter(String pathReferenceSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.AddOnResultFetcher fetcher(String pathAccountSid, String pathReferenceSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.AddOnResultFetcher fetcher(String pathReferenceSid, String pathSid)
com.twilio.rest.api.v2010.account.recording.AddOnResultReader reader(String pathAccountSid, String pathReferenceSid)
com.twilio.rest.api.v2010.account.recording.AddOnResultReader reader(String pathReferenceSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathReferenceSid* | The SID of the recording to which the result to delete belongs | String
| deleter | *pathSid* | The unique string that identifies the resource to delete | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathReferenceSid* | The SID of the recording to which the result to delete belongs | String
| fetcher | *pathSid* | The unique string that identifies the resource to fetch | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathReferenceSid* | The SID of the recording to which the result to delete belongs | String
|===




==== notification


The notification has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.NotificationFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.NotificationFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.NotificationReader reader()
com.twilio.rest.api.v2010.account.NotificationReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== sip-domain-ip-access-control-list-mapping


The sip-domain-ip-access-control-list-mapping has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingCreator creator(String pathAccountSid, String pathDomainSid, String ipAccessControlListSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingCreator creator(String pathDomainSid, String ipAccessControlListSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingDeleter deleter(String pathAccountSid, String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingDeleter deleter(String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingFetcher fetcher(String pathAccountSid, String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingFetcher fetcher(String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingReader reader(String pathAccountSid, String pathDomainSid)
com.twilio.rest.api.v2010.account.sip.domain.IpAccessControlListMappingReader reader(String pathDomainSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *ipAccessControlListSid* | The unique id of the IP access control list to map to the SIP domain | String
| creator | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| creator | *pathDomainSid* | A string that uniquely identifies the SIP Domain | String
| deleter | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| deleter | *pathDomainSid* | A string that uniquely identifies the SIP Domain | String
| deleter | *pathSid* | A 34 character string that uniquely identifies the resource to delete. | String
| fetcher | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| fetcher | *pathDomainSid* | A string that uniquely identifies the SIP Domain | String
| fetcher | *pathSid* | A 34 character string that uniquely identifies the resource to fetch. | String
| reader | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| reader | *pathDomainSid* | A string that uniquely identifies the SIP Domain | String
|===




==== sip-domain


The sip-domain has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.DomainCreator creator(String domainName)
com.twilio.rest.api.v2010.account.sip.DomainCreator creator(String pathAccountSid, String domainName)
com.twilio.rest.api.v2010.account.sip.DomainDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.DomainDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.sip.DomainFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.DomainFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.sip.DomainReader reader()
com.twilio.rest.api.v2010.account.sip.DomainReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.sip.DomainUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.DomainUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *domainName* | The unique address on Twilio to route SIP traffic | String
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resource to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== address


The address has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.AddressCreator creator(String customerName, String street, String city, String region, String postalCode, String isoCountry)
com.twilio.rest.api.v2010.account.AddressCreator creator(String pathAccountSid, String customerName, String street, String city, String region, String postalCode, String isoCountry)
com.twilio.rest.api.v2010.account.AddressDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.AddressDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.AddressFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.AddressFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.AddressReader reader()
com.twilio.rest.api.v2010.account.AddressReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.AddressUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.AddressUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *city* | The city of the new address | String
| creator | *customerName* | The name to associate with the new address | String
| creator | *isoCountry* | The ISO country code of the new address | String
| creator | *pathAccountSid* | The SID of the Account that will be responsible for the new Address resource | String
| creator | *postalCode* | The postal code of the new address | String
| creator | *region* | The state or region of the new address | String
| creator | *street* | The number and street address of the new address | String
| deleter | *pathAccountSid* | The SID of the Account that is responsible for the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that is responsible for this address | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that is responsible for this address | String
| updater | *pathAccountSid* | The SID of the Account that is responsible for the resource to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== message-media


The message-media has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.message.MediaDeleter deleter(String pathAccountSid, String pathMessageSid, String pathSid)
com.twilio.rest.api.v2010.account.message.MediaDeleter deleter(String pathMessageSid, String pathSid)
com.twilio.rest.api.v2010.account.message.MediaFetcher fetcher(String pathAccountSid, String pathMessageSid, String pathSid)
com.twilio.rest.api.v2010.account.message.MediaFetcher fetcher(String pathMessageSid, String pathSid)
com.twilio.rest.api.v2010.account.message.MediaReader reader(String pathAccountSid, String pathMessageSid)
com.twilio.rest.api.v2010.account.message.MediaReader reader(String pathMessageSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resource(s) to delete | String
| deleter | *pathMessageSid* | The SID of the Message resource that this Media resource belongs to | String
| deleter | *pathSid* | The unique string that identifies this resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| fetcher | *pathMessageSid* | The SID of the Message resource that this Media resource belongs to | String
| fetcher | *pathSid* | The unique string that identifies this resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resource(s) to read | String
| reader | *pathMessageSid* | The SID of the Message resource that this Media resource belongs to | String
|===




==== sip-ip-access-control-list-ip-address


The sip-ip-access-control-list-ip-address has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressCreator creator(String pathAccountSid, String pathIpAccessControlListSid, String friendlyName, String ipAddress)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressCreator creator(String pathIpAccessControlListSid, String friendlyName, String ipAddress)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressDeleter deleter(String pathAccountSid, String pathIpAccessControlListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressDeleter deleter(String pathIpAccessControlListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressFetcher fetcher(String pathAccountSid, String pathIpAccessControlListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressFetcher fetcher(String pathIpAccessControlListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressReader reader(String pathAccountSid, String pathIpAccessControlListSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressReader reader(String pathIpAccessControlListSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressUpdater updater(String pathAccountSid, String pathIpAccessControlListSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.ipaccesscontrollist.IpAddressUpdater updater(String pathIpAccessControlListSid, String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *friendlyName* | A human readable descriptive text for this resource, up to 64 characters long. | String
| creator | *ipAddress* | An IP address in dotted decimal notation from which you want to accept traffic. Any SIP requests from this IP address will be allowed by Twilio. IPv4 only supported today. | String
| creator | *pathAccountSid* | The unique sid that identifies this account | String
| creator | *pathIpAccessControlListSid* | The IpAccessControlList Sid with which to associate the created IpAddress resource | String
| deleter | *pathAccountSid* | The unique sid that identifies this account | String
| deleter | *pathIpAccessControlListSid* | The IpAccessControlList Sid with which to associate the created IpAddress resource | String
| deleter | *pathSid* | A string that identifies the resource to delete | String
| fetcher | *pathAccountSid* | The unique sid that identifies this account | String
| fetcher | *pathIpAccessControlListSid* | The IpAccessControlList Sid with which to associate the created IpAddress resource | String
| fetcher | *pathSid* | A string that identifies the IpAddress resource to fetch | String
| reader | *pathAccountSid* | The unique sid that identifies this account | String
| reader | *pathIpAccessControlListSid* | The IpAccessControlList Sid with which to associate the created IpAddress resource | String
| updater | *pathAccountSid* | The unique sid that identifies this account | String
| updater | *pathIpAccessControlListSid* | The IpAccessControlList Sid with which to associate the created IpAddress resource | String
| updater | *pathSid* | A string that identifies the IpAddress resource to update | String
|===




==== available-phone-number-country


The available-phone-number-country has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.AvailablePhoneNumberCountryFetcher fetcher(String pathAccountSid, String pathCountryCode)
com.twilio.rest.api.v2010.account.AvailablePhoneNumberCountryFetcher fetcher(String pathCountryCode)
com.twilio.rest.api.v2010.account.AvailablePhoneNumberCountryReader reader()
com.twilio.rest.api.v2010.account.AvailablePhoneNumberCountryReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathAccountSid* | The SID of the Account requesting the available phone number Country resource | String
| fetcher | *pathCountryCode* | The ISO country code of the country to fetch available phone number information about | String
| reader | *pathAccountSid* | The SID of the Account requesting the available phone number Country resources | String
|===




==== usage-record-yearly


The usage-record-yearly has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.YearlyReader reader()
com.twilio.rest.api.v2010.account.usage.record.YearlyReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== queue


The queue has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.QueueCreator creator(String friendlyName)
com.twilio.rest.api.v2010.account.QueueCreator creator(String pathAccountSid, String friendlyName)
com.twilio.rest.api.v2010.account.QueueDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.QueueDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.QueueFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.QueueFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.QueueReader reader()
com.twilio.rest.api.v2010.account.QueueReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.QueueUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.QueueUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *friendlyName* | A string to describe this resource | String
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| deleter | *pathAccountSid* | The SID of the Account that created the resource(s) to delete | String
| deleter | *pathSid* | The unique string that identifies this resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| fetcher | *pathSid* | The unique string that identifies this resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| updater | *pathAccountSid* | The SID of the Account that created the resource(s) to update | String
| updater | *pathSid* | The unique string that identifies this resource | String
|===




==== transcription


The transcription has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.TranscriptionDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.TranscriptionDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.TranscriptionFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.TranscriptionFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.TranscriptionReader reader()
com.twilio.rest.api.v2010.account.TranscriptionReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== sip-domain-credential-list-mapping


The sip-domain-credential-list-mapping has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingCreator creator(String pathAccountSid, String pathDomainSid, String credentialListSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingCreator creator(String pathDomainSid, String credentialListSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingDeleter deleter(String pathAccountSid, String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingDeleter deleter(String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingFetcher fetcher(String pathAccountSid, String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingFetcher fetcher(String pathDomainSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingReader reader(String pathAccountSid, String pathDomainSid)
com.twilio.rest.api.v2010.account.sip.domain.CredentialListMappingReader reader(String pathDomainSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *credentialListSid* | A string that identifies the CredentialList resource to map to the SIP domain | String
| creator | *pathAccountSid* | The unique sid that identifies this account | String
| creator | *pathDomainSid* | A string that identifies the SIP Domain for which the CredentialList resource will be mapped | String
| deleter | *pathAccountSid* | The unique sid that identifies this account | String
| deleter | *pathDomainSid* | A string that identifies the SIP Domain for which the CredentialList resource will be mapped | String
| deleter | *pathSid* | A string that identifies the resource to delete | String
| fetcher | *pathAccountSid* | The unique sid that identifies this account | String
| fetcher | *pathDomainSid* | A string that identifies the SIP Domain for which the CredentialList resource will be mapped | String
| fetcher | *pathSid* | A string that identifies the resource to fetch | String
| reader | *pathAccountSid* | The unique sid that identifies this account | String
| reader | *pathDomainSid* | A string that identifies the SIP Domain for which the CredentialList resource will be mapped | String
|===




==== call-feedback


The call-feedback has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.call.FeedbackCreator creator(String pathAccountSid, String pathCallSid, Integer qualityScore)
com.twilio.rest.api.v2010.account.call.FeedbackCreator creator(String pathCallSid, Integer qualityScore)
com.twilio.rest.api.v2010.account.call.FeedbackFetcher fetcher(String pathAccountSid, String pathCallSid)
com.twilio.rest.api.v2010.account.call.FeedbackFetcher fetcher(String pathCallSid)
com.twilio.rest.api.v2010.account.call.FeedbackUpdater updater(String pathAccountSid, String pathCallSid, Integer qualityScore)
com.twilio.rest.api.v2010.account.call.FeedbackUpdater updater(String pathCallSid, Integer qualityScore)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The unique sid that identifies this account | String
| creator | *pathCallSid* | The call sid that uniquely identifies the call | String
| creator | *qualityScore* | The call quality expressed as an integer from 1 to 5 | Integer
| fetcher | *pathAccountSid* | The unique sid that identifies this account | String
| fetcher | *pathCallSid* | The call sid that uniquely identifies the call | String
| updater | *pathAccountSid* | The unique sid that identifies this account | String
| updater | *pathCallSid* | The call sid that uniquely identifies the call | String
| updater | *qualityScore* | The call quality expressed as an integer from 1 to 5 | Integer
|===




==== key


The key has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.KeyDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.KeyDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.KeyFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.KeyFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.KeyReader reader()
com.twilio.rest.api.v2010.account.KeyReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.KeyUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.KeyUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resources to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== incoming-phone-number-toll-free


The incoming-phone-number-toll-free has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.incomingphonenumber.TollFreeCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.incomingphonenumber.TollFreeCreator creator(com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.incomingphonenumber.TollFreeReader reader()
com.twilio.rest.api.v2010.account.incomingphonenumber.TollFreeReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *phoneNumber* | The phone number to purchase in E.164 format | PhoneNumber
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== token


The token has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.TokenCreator creator()
com.twilio.rest.api.v2010.account.TokenCreator creator(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
|===




==== short-code


The short-code has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.ShortCodeFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ShortCodeFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.ShortCodeReader reader()
com.twilio.rest.api.v2010.account.ShortCodeReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.ShortCodeUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ShortCodeUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| fetcher | *pathSid* | The unique string that identifies this resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resource(s) to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resource(s) to update | String
| updater | *pathSid* | The unique string that identifies this resource | String
|===




==== available-phone-number-country-toll-free


The available-phone-number-country-toll-free has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.availablephonenumbercountry.TollFreeReader reader(String pathAccountSid, String pathCountryCode)
com.twilio.rest.api.v2010.account.availablephonenumbercountry.TollFreeReader reader(String pathCountryCode)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account requesting the AvailablePhoneNumber resources | String
| reader | *pathCountryCode* | The ISO Country code of the country from which to read phone numbers | String
|===




==== usage-record-monthly


The usage-record-monthly has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.usage.record.MonthlyReader reader()
com.twilio.rest.api.v2010.account.usage.record.MonthlyReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== sip-ip-access-control-list


The sip-ip-access-control-list has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.IpAccessControlListCreator creator(String friendlyName)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListCreator creator(String pathAccountSid, String friendlyName)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListReader reader()
com.twilio.rest.api.v2010.account.sip.IpAccessControlListReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListUpdater updater(String pathAccountSid, String pathSid, String friendlyName)
com.twilio.rest.api.v2010.account.sip.IpAccessControlListUpdater updater(String pathSid, String friendlyName)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *friendlyName* | A human readable description of this resource | String
| creator | *pathAccountSid* | The unique sid that identifies this account | String
| deleter | *pathAccountSid* | The unique sid that identifies this account | String
| deleter | *pathSid* | A string that identifies the resource to delete | String
| fetcher | *pathAccountSid* | The unique sid that identifies this account | String
| fetcher | *pathSid* | A string that identifies the resource to fetch | String
| reader | *pathAccountSid* | The unique sid that identifies this account | String
| updater | *friendlyName* | A human readable description of this resource | String
| updater | *pathAccountSid* | The unique sid that identifies this account | String
| updater | *pathSid* | A string that identifies the resource to update | String
|===




==== connect-app


The connect-app has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.ConnectAppDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ConnectAppDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.ConnectAppFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ConnectAppFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.ConnectAppReader reader()
com.twilio.rest.api.v2010.account.ConnectAppReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.ConnectAppUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.ConnectAppUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resources to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== address-dependent-phone-number


The address-dependent-phone-number has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.address.DependentPhoneNumberReader reader(String pathAccountSid, String pathAddressSid)
com.twilio.rest.api.v2010.account.address.DependentPhoneNumberReader reader(String pathAddressSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| reader | *pathAddressSid* | The SID of the Address resource associated with the phone number | String
|===




==== signing-key


The signing-key has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.SigningKeyDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.SigningKeyDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.SigningKeyFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.SigningKeyFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.SigningKeyReader reader()
com.twilio.rest.api.v2010.account.SigningKeyReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.SigningKeyUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.SigningKeyUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The account_sid | String
| deleter | *pathSid* | The sid | String
| fetcher | *pathAccountSid* | The account_sid | String
| fetcher | *pathSid* | The sid | String
| reader | *pathAccountSid* | The account_sid | String
| updater | *pathAccountSid* | The account_sid | String
| updater | *pathSid* | The sid | String
|===




==== outgoing-caller-id


The outgoing-caller-id has 4 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.OutgoingCallerIdDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.OutgoingCallerIdDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.OutgoingCallerIdFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.OutgoingCallerIdFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.OutgoingCallerIdReader reader()
com.twilio.rest.api.v2010.account.OutgoingCallerIdReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.OutgoingCallerIdUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.OutgoingCallerIdUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resources to update | String
| updater | *pathSid* | The unique string that identifies the resource | String
|===




==== call


The call has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.CallCreator creator(String pathAccountSid, com.twilio.type.Endpoint to, com.twilio.type.Endpoint from, String applicationSid)
com.twilio.rest.api.v2010.account.CallCreator creator(String pathAccountSid, com.twilio.type.Endpoint to, com.twilio.type.Endpoint from, com.twilio.type.Twiml twiml)
com.twilio.rest.api.v2010.account.CallCreator creator(String pathAccountSid, com.twilio.type.Endpoint to, com.twilio.type.Endpoint from, java.net.URI url)
com.twilio.rest.api.v2010.account.CallCreator creator(com.twilio.type.Endpoint to, com.twilio.type.Endpoint from, String applicationSid)
com.twilio.rest.api.v2010.account.CallCreator creator(com.twilio.type.Endpoint to, com.twilio.type.Endpoint from, com.twilio.type.Twiml twiml)
com.twilio.rest.api.v2010.account.CallCreator creator(com.twilio.type.Endpoint to, com.twilio.type.Endpoint from, java.net.URI url)
com.twilio.rest.api.v2010.account.CallDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.CallDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.CallFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.CallFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.CallReader reader()
com.twilio.rest.api.v2010.account.CallReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.CallUpdater updater(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.CallUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *applicationSid* | The SID of the Application resource that will handle the call | String
| creator | *from* | Twilio number from which to originate the call | Endpoint
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *to* | Phone number, SIP address, or client identifier to call | Endpoint
| creator | *twiml* | TwiML instructions for the call | Twiml
| creator | *url* | The absolute URL that returns TwiML for this call | URI
| deleter | *pathAccountSid* | The SID of the Account that created the resource(s) to delete | String
| deleter | *pathSid* | The unique string that identifies this resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource(s) to fetch | String
| fetcher | *pathSid* | The SID of the Call resource to fetch | String
| reader | *pathAccountSid* | The SID of the Account that created the resource(s) to read | String
| updater | *pathAccountSid* | The SID of the Account that created the resource(s) to update | String
| updater | *pathSid* | The unique string that identifies this resource | String
|===




==== incoming-phone-number-local


The incoming-phone-number-local has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.incomingphonenumber.LocalCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.incomingphonenumber.LocalCreator creator(com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.incomingphonenumber.LocalReader reader()
com.twilio.rest.api.v2010.account.incomingphonenumber.LocalReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *phoneNumber* | The phone number to purchase in E.164 format | PhoneNumber
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== message-feedback


The message-feedback has 1 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.message.FeedbackCreator creator(String pathAccountSid, String pathMessageSid)
com.twilio.rest.api.v2010.account.message.FeedbackCreator creator(String pathMessageSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *pathMessageSid* | The SID of the Message resource for which the feedback was provided | String
|===




==== recording


The recording has 3 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.RecordingDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.RecordingDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.RecordingFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.RecordingFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.RecordingReader reader()
com.twilio.rest.api.v2010.account.RecordingReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| deleter | *pathAccountSid* | The SID of the Account that created the resources to delete | String
| deleter | *pathSid* | The unique string that identifies the resource | String
| fetcher | *pathAccountSid* | The SID of the Account that created the resource to fetch | String
| fetcher | *pathSid* | The unique string that identifies the resource | String
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== incoming-phone-number-mobile


The incoming-phone-number-mobile has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.incomingphonenumber.MobileCreator creator(String pathAccountSid, com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.incomingphonenumber.MobileCreator creator(com.twilio.type.PhoneNumber phoneNumber)
com.twilio.rest.api.v2010.account.incomingphonenumber.MobileReader reader()
com.twilio.rest.api.v2010.account.incomingphonenumber.MobileReader reader(String pathAccountSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *pathAccountSid* | The SID of the Account that will create the resource | String
| creator | *phoneNumber* | The phone number to purchase in E.164 format | PhoneNumber
| reader | *pathAccountSid* | The SID of the Account that created the resources to read | String
|===




==== account


The account has 2 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.AccountFetcher fetcher()
com.twilio.rest.api.v2010.AccountFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.AccountUpdater updater()
com.twilio.rest.api.v2010.AccountUpdater updater(String pathSid)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| fetcher | *pathSid* | Fetch by unique Account Sid | String
| updater | *pathSid* | Update by unique Account Sid | String
|===




==== sip-credential-list


The sip-credential-list has 5 API method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

----
com.twilio.rest.api.v2010.account.sip.CredentialListCreator creator(String friendlyName)
com.twilio.rest.api.v2010.account.sip.CredentialListCreator creator(String pathAccountSid, String friendlyName)
com.twilio.rest.api.v2010.account.sip.CredentialListDeleter deleter(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.CredentialListDeleter deleter(String pathSid)
com.twilio.rest.api.v2010.account.sip.CredentialListFetcher fetcher(String pathAccountSid, String pathSid)
com.twilio.rest.api.v2010.account.sip.CredentialListFetcher fetcher(String pathSid)
com.twilio.rest.api.v2010.account.sip.CredentialListReader reader()
com.twilio.rest.api.v2010.account.sip.CredentialListReader reader(String pathAccountSid)
com.twilio.rest.api.v2010.account.sip.CredentialListUpdater updater(String pathAccountSid, String pathSid, String friendlyName)
com.twilio.rest.api.v2010.account.sip.CredentialListUpdater updater(String pathSid, String friendlyName)

----

The API methods has the following set of options listed in the following table:
[width="100%",cols="1,2,5,2",options="header"]
|===
| Method | Name | Description | Type
| creator | *friendlyName* | Human readable descriptive text | String
| creator | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| deleter | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| deleter | *pathSid* | Delete by unique credential list Sid | String
| fetcher | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| fetcher | *pathSid* | Fetch by unique credential list Sid | String
| reader | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| updater | *friendlyName* | Human readable descriptive text | String
| updater | *pathAccountSid* | The unique id of the Account that is responsible for this resource | String
| updater | *pathSid* | Update by unique credential list Sid | String
|===
// endpoint options: END

== Producer Endpoints:

Producer endpoints can use endpoint prefixes followed by endpoint names
and associated options described next. A shorthand alias can be used for
all of the endpoints. The endpoint URI MUST contain a prefix.

Any of the endpoint options can be provided in either the endpoint URI,
or dynamically in a message header. The message header name must be of
the format *`CamelTwilio.<option>`*. Note that the *`inBody`* option
overrides message header, i.e. the endpoint option *`inBody=option`*
would override a *`CamelTwilio.option`* header.

Endpoint can be one of:

[width="100%",cols="20%,20%,60%",options="header"]
|=======================================================================
| Endpoint  | Shorthand Alias | Description
| *creator* | create          | Make the request to the Twilio API to perform the create
| *deleter* | delete          | Make the request to the Twilio API to perform the delete
| *fetcher* | fetch           | Make the request to the Twilio API to perform the fetch
| *reader*  | read            | Make the request to the Twilio API to perform the read
| *updater* | update          | Make the request to the Twilio API to perform the update
|=======================================================================

Available endpoints differ depending on the endpoint prefixes.

For more information on the endpoints and options see API documentation at:
https://www.twilio.com/docs/libraries/reference/twilio-java/index.html


== Consumer Endpoints:

Any of the producer endpoints can be used as a consumer endpoint.
Consumer endpoints can use
http://camel.apache.org/polling-consumer.html#PollingConsumer-ScheduledPollConsumerOptions[Scheduled
Poll Consumer Options] to schedule endpoint invocation.
Consumer endpoints that return an array or collection will
generate one exchange per element, and their routes will be executed
once for each exchange.

If you want to receive calls or messages from Twilio and respond to them
using a Camel consumer endpoint, you can use other HTTP-based components
such as *camel-servlet*, *camel-undertow*, *camel-jetty*, and *camel-netty-http*
to respond with https://www.twilio.com/docs/api/twiml[TwiML].


== Message header

Any of the options can be provided in a message header for producer
endpoints with *CamelTwilio.* prefix.


== Message body

All result message bodies utilize objects provided by the Twilio Java SDK.
Producer endpoints can specify the option name for incoming message body
in the *inBody* endpoint parameter.

include::camel-spring-boot::page$twilio-starter.adoc[]
